on: 
  workflow_call:
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: terraform apply
        run: make dev-apply
  test:
    runs-on: [self-hosted, linux, x64]
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: terraform apply
        run: make dev-apply