on:
  workflow_call:
    inputs:
      app_type: 
        required: true
        type: string
jobs:
  docker-build-push:
    if:  inputs.app_type == 'java'
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name : download dependencies
        run : |
          if [${inputs.app_type}=='java']; then
            mvn package
          fi

      - name: Docker build
        run : |
          docker build . 

