on:
  workflow_call:
    inputs:
      app_type: 
        required: true
        type: string
jobs:
  nodejs:
    if:  inputs.app_type == 'nodejs'
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: nodejs
        run: echo Hello, world!

  java:
    if:  inputs.app_type == 'java'
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: java
        run: echo Hello, world!

  python:
    if:  inputs.app_type == 'python'
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: python
        run: echo Hello, world!