on:
  workflow_call:
    inputs:
      app_type: 
        required: true
        type: string
      app_name: 
        required: true
        type: string
jobs:
  docker-build-push:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name : download dependencies
        run : |
          if [ "${{inputs.app_type}}" == "java" ]; then
            mvn package
          fi
          if [ "${{inputs.app_type}}" == "nodejs" ]; then
            npm install
          fi
          
      - name: Ensure Docker is running and restart if needed
        run: |
          CURRENT_USER=$(whoami)
          if [ "$CURRENT_USER" = "github-runner" ] && groups "$CURRENT_USER" | grep -q '\bdocker\b'; then
            echo "Restarting Docker for user $CURRENT_USER..."
            sudo systemctl restart docker
            sudo systemctl status docker --no-pager
          else
            echo "User $CURRENT_USER is not github-runner or not in docker group. Skipping Docker restart."
          fi


      - name: Docker build
        run : |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533567530972.dkr.ecr.us-east-1.amazonaws.com
          docker build -t 533567530972.dkr.ecr.us-east-1.amazonaws.com/${{inputs.app_name}}:${GITHUB_SHA} .
          docker push 533567530972.dkr.ecr.us-east-1.amazonaws.com/${{inputs.app_name}}:${GITHUB_SHA}

