on:
  workflow_call:
    inputs:
      app_type: 
        required: true
        type: string
jobs:
  docker-build-push:
    if:  inputs.app_type == 'java'
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name : download dependencies
        run : |
          if [${inputs.app_type}=='nginx']; then
            mvn package
          fi

      - name: Docker build
        run : |
          docker build . 
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533567530972.dkr.ecr.us-east-1.amazonaws.com
          docker build frontend:latest 533567530972.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 533567530972.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

