on: 
  workflow_call:
    inputs:
      app_type: 
        required: true
        type: string
jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  test:
    runs-on: [self-hosted, linux, x64]
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!