on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_env:
        required: true
        type: string
      enabled:
        required : true
        type : string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'DevOpsProjectsOrganization/roboshop-helm'
          path: 'helm'
      - name: Deploy
        run: |
          cd helm
          aws eks update-kubeconfig --region us-east-1 --name ${{ inputs.app_env }} 
          helm upgrade -i ${{ inputs.app_name }} . -f env-${{ inputs.app_env }}/${{ inputs.app_name }}.yml --values ./values.yml --set schema.enabled=${{ inputs.enabled }}