on:
  workflow_call:
    inputs:
      app_name: 
        required: true
        type: string
      app_env:
        required : true
        type : string
      enabled:
        required : true
        type : string
jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v5
        with:
          repository: DevOpsProjectsOrganization/roboshop-helm  
          path: helm

      - uses: actions/checkout@v5
        with:
          path: app

      - name : deploy the app in dev
        run : |
          cd helm
          aws eks update-kubeconfig --region us-east-1 --name ${{ inputs.app_env }} 
          aws eks get-token --cluster-name dev --region us-east-1
          helm upgrade -i ${{ inputs.app_name }} . -f env-${{ inputs.app_env }}/${{ inputs.app_name }}.yml --values ./values.yml --set schema.enabled=${{ inputs.enabled }}

          
