on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_env:
        required: true
        type: string
      enabled:
        required : true
        type : string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'DevOpsProjectsOrganization/roboshop-helm'
          path: 'helm'

      - name: Debug Helm folder
        run: ls -R helm

      - name: update kube config and create secrets for all services
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ inputs.app_env }} 
          cd helm
          helm upgrade -i ${{ inputs.app_name }} . -f env-${{ inputs.app_env }}/${{ inputs.app_name }}.yml \
            --values ./values.yml \
            --set imageTag=${GITHUB_SHA} \
            --set schema.enabled=${{ inputs.enabled }} \
            --show-only templates/external-secret.yml
      
      - name : Deploy argo cd
        run : |
        #  cd helm
          argocd login argocd-dev.sdevops.shop \
            --insecure \
            --username admin \
            --password $(kubectl get secrets -n tools argocd-initial-admin-secret -o=jsonpath='{.data.password}' | base64 -d) \
            --grpc-web
          argocd app create ${{ inputs.app_name }} \
            --repo https://github.com/DevOpsProjectsOrganization/roboshop-helm \
            --path . \
            --dest-namespace default \
            --dest-server https://kubernetes.default.svc \
            --values env-${{ inputs.app_env }}/${{ inputs.app_name }}.yml \
            --values ./values.yml \
            --helm-set imageTag=${GITHUB_SHA} \
            --helm-set schema.enabled=${{ inputs.enabled }} \
            --sync-policy automatic \
            --upsert